CREATE DATABASE IF NOT EXISTS CBDB;
DROP TABLE IF EXISTS PATIENTS, SPECIALTY_GROUP, SPECIALTY, CLINICIAN, PATIENTS_CLINITIAN, MEDICAL_RECORDS, RECORD_SPECIALTIES, LOGIN;


CREATE USER IF NOT EXISTS 'cbdb_su'@'localhost' IDENTIFIED BY 'password';
GRANT ALL ON CBDB.* TO 'cbdb_su'@'localhost' IDENTIFIED BY 'password';

USE CBDB;
CREATE TABLE IF NOT EXISTS PATIENTS (
	PatientID INT NOT NULL,
	PatientName VARCHAR(255) NOT NULL,
	DateOfBirth DATE NOT NULL,
	/*grupo sanguineo, sexo*/
PRIMARY KEY(PatientID)
);
CREATE TABLE IF NOT EXISTS SPECIALTY_GROUP(
	SpecialtyGroupID VARCHAR(255) NOT NULL,
PRIMARY KEY(SpecialtyGroupID)
);
CREATE TABLE IF NOT EXISTS SPECIALTY(
	SpecialtyID VARCHAR(255) NOT NULL,
	SpecialtyGroupID VARCHAR(255) NOT NULL,
PRIMARY KEY(SpecialtyID)
);
CREATE TABLE IF NOT EXISTS CLINICIAN(
	ClinicianID INT NOT NULL,
	SpecialtyID VARCHAR(255) NOT NULL,
	ClinicianUsername VARCHAR(255) NOT NULL,
PRIMARY KEY(ClinicianID),
FOREIGN KEY(SpecialtyID) REFERENCES SPECIALTY(SpecialtyID)
);
CREATE TABLE IF NOT EXISTS PATIENTS_CLINITIAN(
	PDID INT NOT NULL,
	PatientID INT NOT NULL,
	ClinicianID INT NOT NULL,
PRIMARY KEY(PDID),
FOREIGN KEY(PatientID) REFERENCES PATIENTS(PatientID),
FOREIGN KEY(ClinicianID) REFERENCES CLINICIAN(ClinicianID)
);
CREATE TABLE IF NOT EXISTS MEDICAL_RECORDS(
	RID INT NOT NULL,
	PatientID INT NOT NULL,
	ClinicianID INT NOT NULL,
	RSpecialtiesID INT NOT NULL,
	RecordHash INT NOT NULL,
	RecordInfo VARBINARY(1024),
PRIMARY KEY(RID),
FOREIGN KEY(PatientID) REFERENCES PATIENTS(PatientID),
FOREIGN KEY(ClinicianID) REFERENCES CLINICIAN(ClinicianID)
);
CREATE TABLE IF NOT EXISTS RECORD_SPECIALTIES(
	RSID INT NOT NULL,
	RSpecialtiesID INT NOT NULL,
	SpecialtyID VARCHAR(255) NOT NULL,
PRIMARY KEY(RSID)
);
CREATE TABLE IF NOT EXISTS LOGIN(
	Username VARCHAR(255) NOT NULL,
	Salt INT NOT NULL,
	Hash INT NOT NULL,
	ClinicianID INT NOT NULL,
PRIMARY KEY(Username)
);
