DROP DATABASE IF EXISTS CBDB;

CREATE DATABASE CBDB;
USE CBDB;

CREATE USER IF NOT EXISTS 'cbdb_su'@'localhost' IDENTIFIED BY 'password';
GRANT ALL ON CBDB.* TO 'cbdb_su'@'localhost' IDENTIFIED BY 'password';

CREATE TABLE IF NOT EXISTS PATIENTS (
	PatientID INT NOT NULL,
	PatientName VARCHAR(255) NOT NULL,
	DateOfBirth DATE NOT NULL,
	/*grupo sanguineo, sexo*/
PRIMARY KEY(PatientID)
);
CREATE TABLE IF NOT EXISTS SPECIALTY_GROUP(
	SpecialtyGroupID VARCHAR(255) NOT NULL,
PRIMARY KEY(SpecialtyGroupID)
);
CREATE TABLE IF NOT EXISTS SPECIALTY(
	SpecialtyID VARCHAR(255) NOT NULL,
	SpecialtyGroupID VARCHAR(255) NOT NULL,
PRIMARY KEY(SpecialtyID)
);
CREATE TABLE IF NOT EXISTS CLINICIAN(
	ClinicianID INT NOT NULL,
	SpecialtyID VARCHAR(255) NOT NULL,
	ClinicianUsername VARCHAR(255) NOT NULL,
	ClinicianName VARCHAR(255) NOT NULL,
PRIMARY KEY(ClinicianID),
FOREIGN KEY(SpecialtyID) REFERENCES SPECIALTY(SpecialtyID)
);
CREATE TABLE IF NOT EXISTS PATIENTS_CLINITIAN(
	PDID INT NOT NULL,
	PatientID INT NOT NULL,
	ClinicianID INT NOT NULL,
PRIMARY KEY(PDID),
FOREIGN KEY(ClinicianID) REFERENCES CLINICIAN(ClinicianID)
);
CREATE TABLE IF NOT EXISTS RECORD_SPECIALTIES(
	RSID INT NOT NULL,
	RecordID INT NOT NULL,
	SpecialtyID VARCHAR(255) NOT NULL,
PRIMARY KEY(RSID)
);
CREATE TABLE IF NOT EXISTS MEDICAL_RECORDS(
	RecordID INT NOT NULL,
	PatientID INT NOT NULL,
	ClinicianID INT NOT NULL,
	RecordHash VARCHAR(255) NOT NULL,
	RecordInfo VARBINARY(1024),
PRIMARY KEY(RecordID),
FOREIGN KEY(PatientID) REFERENCES PATIENTS(PatientID),
FOREIGN KEY(ClinicianID) REFERENCES CLINICIAN(ClinicianID)
);
CREATE TABLE IF NOT EXISTS LOGIN(
	Username VARCHAR(255) NOT NULL,
	Salt VARCHAR(255) NOT NULL,
	Hash VARCHAR(255) NOT NULL,
	ClinicianID INT NOT NULL,
PRIMARY KEY(Username)
);
